//! Protobuf wire types for imbh's typed query-API inputs — the control plane a Go / FFI binding
//! sends across the boundary (ARCHITECTURE.md §10.17).
//!
//! The types here are generated by prost from [`proto/imbh/v1/query.proto`](../proto/imbh/v1/query.proto)
//! at build time (via protox — no system `protoc`). This crate is the wire schema and nothing more:
//! the `TryFrom<imbh_proto::…>` mappings onto the domain builders (`LogQuery`/`TraceQuery`/…) live in
//! the `imbh` facade behind its `proto` feature, so this crate stays dependency-light (prost only)
//! and out of the default footprint graph unless a host opts into `proto`.
//!
//! Results are **not** modeled as protobuf rows: bulk result batches travel as Arrow (zero-copy via
//! the Arrow C Data Interface at the FFI layer, or Arrow IPC bytes as a fallback); only the small
//! [`QueryStats`] metadata envelope is carried here.

// prost-generated module for `package imbh.v1;`.
include!(concat!(env!("OUT_DIR"), "/imbh.v1.rs"));
